{
 "title": "Memory Usage",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Heap Size Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "nodejs_heap_size_used_bytes{instance=\"host.docker.internal:3000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Size Total Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "nodejs_heap_size_total_bytes{instance=\"host.docker.internal:3000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Resident Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"nest-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC Duration Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "nodejs_gc_duration_seconds_count{instance=\"host.docker.internal:3000\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}